name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Changed from 'main' to 'master'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build . -t my-app:latest

    - name: Run tests
      run: |
        docker run --rm my-app:latest npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Docker image
      run: |
        docker tag my-app:latest dower983/my-task-manager:latest

    - name: Push Docker image
      run: |
        docker push dower983/my-task-manager:latest
