name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build ./backend -t my-backend-app:latest
          docker build ./frontend -t my-frontend-app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag my-backend-app:latest your-dockerhub-username/my-backend-app:latest
          docker push your-dockerhub-username/my-backend-app:latest

          docker tag my-frontend-app:latest your-dockerhub-username/my-frontend-app:latest
          docker push your-dockerhub-username/my-frontend-app:latest
