name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Docker image
        run: |
          docker build -f backend/Dockerfile -t my-backend-app:latest backend/

      - name: Build Frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t my-frontend-app:latest frontend/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Backend Docker image
        run: |
          docker tag my-backend-app:latest my-dockerhub-username/my-backend-app:latest
          docker push my-dockerhub-username/my-backend-app:latest

      - name: Push Frontend Docker image
        run: |
          docker tag my-frontend-app:latest my-dockerhub-username/my-frontend-app:latest
          docker push my-dockerhub-username/my-frontend-app:latest
