name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # This step uses a GitHub action, so no run command is included
        # Custom logging is not applicable directly here

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # This step uses a GitHub action, so no run command is included
        # Custom logging is not applicable directly here

      - name: Build Docker images - Backend
        run: |
          echo "Starting to build backend Docker image..."
          docker build -t dower983/my-task-manager-backend:latest -f backend/Dockerfile .
          echo "Backend Docker image built successfully."

      - name: Build Docker images - Frontend
        run: |
          echo "Starting to build frontend Docker image..."
          docker build -t dower983/my-task-manager-frontend:latest -f frontend/Dockerfile .
          echo "Frontend Docker image built successfully."

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # This step uses a GitHub action, so no run command is included
        # Custom logging is not applicable directly here

      - name: Push Docker images - Backend
        run: |
          echo "Pushing backend Docker image to Docker Hub..."
          docker push dower983/my-task-manager-backend:latest
          echo "Backend Docker image pushed successfully."

      - name: Push Docker images - Frontend
        run: |
          echo "Pushing frontend Docker image to Docker Hub..."
          docker push dower983/my-task-manager-frontend:latest
          echo "Frontend Docker image pushed successfully."
