name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend Docker image
        run: |
          docker build ./backend -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-task-manager-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-task-manager-backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build ./frontend -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-task-manager-frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-task-manager-frontend:latest
